---
- include_tasks: setup.yml
- include_tasks: configure.yml
- include_tasks: authentication.yml
- include_tasks: system-users.yml
- include_tasks: virtual-users.yml

- include_tasks: tls-certificate.yml
  when: pureftpd_config.TLS | default(0) | int() > 0
